SELECT STUDENT.STU_NO, STUDENT.STU_NAME
FROM STUDENT
JOIN ENROL ON STUDENT.STU_NO = ENROL.STU_NO
JOIN SUBJECT ON ENROL.SUB_NO = SUBJECT.SUB_NO
WHERE SUBJECT.SUB_NAME = '기계공작법' OR SUBJECT.SUB_NAME = '기초전자실험'
ORDER BY SUBJECT.SUB_NO;

SELECT * FROM SUBJECT;

SELECT STU_NO, STU_NAME
FROM STUDENT
NATURAL JOIN ENROL
NATURAL JOIN SUBJECT
WHERE SUB_NAME = '기계공작법' OR SUB_NAME = '기초전자실험'
ORDER BY STU_NO;

SELECT STUDENT.STU_NO, STUDENT.STU_NAME
FROM STUDENT
JOIN ENROL ON STUDENT.STU_NO = ENROL.STU_NO
JOIN SUBJECT ON ENROL.SUB_NO = SUBJECT.SUB_NO
WHERE STUDENT.STU_GENDER = 'F' OR SUBJECT.SUB_PROF = '구봉규'
ORDER BY STUDENT.STU_NO;

SELECT *
FROM SUBJECT;

---------------------------------------

SELECT TABLE_NAME
FROM USER_TABLES;

SELECT *
FROM STUDENT;

--학생테이블에서 여성인 키가 160~170사이에 학생정보를 검색하라.
SELECT *
FROM STUDENT
WHERE STU_GENDER='F'
AND STU_HEIGHT BETWEEN 160 AND 170;

--수강테이블(ENROL)에서 2015학번미만의 학생들에 대한 별도의 테이블을 만들어라?
SELECT * FROM ENROL;
CREATE TABLE A_ENROL
AS
SELECT *
FROM ENROL
WHERE STU_NO<20150000;

SELECT * FROM A_ENROL;

--20151062학번을 가진 김인중학생이 108번 소프트웨어공학 과목을 수강하여
--92점 데이터를 입력하는 경우임.
--INSERT()문을 수행하는 방법?
--INSERT INTO <T/N>(C/N)VALUES(값들)
INSERT INTO A_ENROL (SUB_NO,STU_NO,ENR_GRADE)
VALUES(108,20151062,92);
SELECT * FROM A_ENROL;
--위의 방법이 오피셜한(정상적인) 방법임.
--20152088학생이 과목번호 109학생이 85점을 등록하여라?
INSERT INTO A_ENROL VALUES(109,20152088,85);
SELECT * FROM A_ENROL;

--20152088조민우 학생이 자동제어(110)과목점수를 알지못하고 이를 등록하는경우
--명시적 방법.
INSERT INTO A_ENROL VALUES(110,20152088,NULL);
SELECT * FROM A_ENROL;
INSERT INTO A_ENROL(SUB_NO,STU_NO)
VALUES(110,20152088);
SELECT * FROM A_ENROL;

--복수행삽입하는 방법?
SELECT * FROM ENROL ORDER BY STU_NO;
SELECT * FROM A_ENROL;

INSERT INTO A_ENROL
SELECT * FROM ENROL
WHERE STU_NO LIKE '2015%';

SELECT * FROM A_ENROL;

--UPDATE()
--A_ENROL테이블의 모든 점수를 5점씩 올려서 출력하라?
--UPDATE <T/N> SET <C/N><변경되는 실행값>
UPDATE A_ENROL
SET ENR_GRADE=ENR_GRADE+5;

--과목번호(SUB_NO)가 101번인 학생에게 점수를 5점 추가하라?
UPDATE A_ENROL
SET ENR_GRADE=ENR_GRADE+5
WHERE SUB_NO=101;

SELECT * FROM A_ENROL;

--과목이름(SUB_NAME)이 '시스템분석설계'인 과목번호인 학생점수를 10점
-- 추가하라?
UPDATE A_ENROL
SET ENR_GRADE=ENR_GRADE+10
WHERE SUB_NO=(SELECT SUB_NO FROM SUBJECT WHERE SUB_NAME='시스템분석설계');

SELECT SUB_NO FROM SUBJECT WHERE SUB_NAME='시스템분석설계';

--DELETE()?
--DELETE FROM <T/N> WHERE <C>
DELETE FROM A_ENROL
WHERE STU_NO=20131001;
SELECT * FROM A_ENROL;

--부질의문이란? SELECT문에 또 SELECT문이 있는 내용이라 하는데..(절이 두개인경우를 의미함)
SELECT * FROM STUDENT;
--학생테이블에서 박희철 학생의 몸무게보다 무거운 학생들의 정보를 출력하라?
SELECT *
FROM STUDENT
WHERE STU_WEIGHT>(SELECT STU_WEIGHT FROM STUDENT WHERE STU_NAME='박희철');

--A_ENROL 테이블에서 과목이름이 '기계요소설계'인 과목번호를 갖는 학과번호를 삭제하라?
DELETE FROM A_ENROL
WHERE SUB_NO=(SELECT SUB_NO FROM SUBJECT WHERE SUB_NAME='기계요소설계');
SELECT SUB_NO FROM SUBJECT WHERE SUB_NAME='기계요소설계';
SELECT * FROM A_ENROL;

--다중행 삭제?
DELETE FROM A_ENROL;

--TCL(TRANACTION CONTROL LANGUAGE):COMMIT/ROLLBACK
CREATE TABLE A_STUDENT
AS
SELECT *
FROM STUDENT
WHERE STU_DEPT IN('기계', '전기전자');
CREATE TABLE B_STUDENT
AS
SELECT *
FROM STUDENT
WHERE STU_DEPT IN('전기전자', '컴퓨터정보');

SELECT * FROM A_STUDENT;
SELECT * FROM B_STUDENT;

DELETE FROM B_STUDENT;
SELECT * FROM B_STUDENT;
ROLLBACK;

--만약에 DDL(CREATE()/ALTER()/TRUNCATE()/DROP())이 수행되면
--자동으로 COMMIT()이 되버린다.
CREATE TABLE C_STUDENT(
STU_NO NUMBER,
STU_AME CHAR(10));

SELECT * FROM A_STUDENT;
DELETE FROM A_STUDENT;
ROLLBACK;

SELECT * FROM A_STUDENT;
INSERT INTO A_STUDENT(STU_NO,STU_NAME)
VALUES(10,'홍');
SELECT * FROM A_STUDENT;
COMMIT;
SELECT TABLE_NAME FROM USER_TABLES;

-- DML의 실전문제입니다.
--실전문제 FOR DML?
--1.사원테이블(EMP)을 이용하여 부서번호(DEPTNO)가 20,30번 부서인
--사원정보를 EMP1의 테이블로 만들어라?

CREATE TABLE EMP1 AS
SELECT *
FROM EMP
WHERE DEPTNO IN (20, 30);

SELECT * FROM EMP;
SELECT * FROM EMP1;

--2.부서테이블(DEPT)을 복사하여 DEPT1테이블을 만들어라?

CREATE TABLE DEPT1 AS
SELECT *
FROM DEPT;

--3.급여등급테이블(SALGRADE)을 SALGRADE1테이블을 만들어라?

SELECT TABLE_NAME FROM USER_TABLES;
SELECT * FROM ENROL;

CREATE TABLE SALGRADE1 (
    GRADE NUMBER,
    LOSAL NUMBER,
    HISAL NUMBER
);

INSERT INTO SALGRADE1 (GRADE, LOSAL, HISAL) VALUES (1, 700, 1200);
INSERT INTO SALGRADE1 (GRADE, LOSAL, HISAL) VALUES (2, 1201, 1400);
INSERT INTO SALGRADE1 (GRADE, LOSAL, HISAL) VALUES (3, 1401, 2000);
INSERT INTO SALGRADE1 (GRADE, LOSAL, HISAL) VALUES (4, 2001, 3000);
INSERT INTO SALGRADE1 (GRADE, LOSAL, HISAL) VALUES (5, 3001, 9999);

SELECT * FROM SALGRADE1;


--4.사원번호7703,사원이름JOSH,사원직무 SALESMAN,상급자사원번호 7566,
--급여1400,커미션0,부서번호20인 사원이 오늘 입사하였다.

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (7703, 'JOSH', 'SALESMAN', 7566, SYSDATE, 1400, 0, 20);

INSERT INTO SALGRADE (GRADE, LOSAL, HISAL)
VALUES (6, 1400, 1400);


--5.사원번호7401,사원이름 HOMER,급여1300,부서번호10인 사원이 입사하였다.

--6.사원번호7323,사원이름 BRANDA,부서번호30,사원번호7499와 동일한 급여를 받는
--사원이 오늘 입사하였다.

--7.사원테이블에서 부서번호가10인 데이터를 EMP1테이블에 삽입하라?

--8.사원번호 7369의 사원직무를 ANALYST로 바꾸시오?

--9.부서번호 20인 직원들의 급여를 10%감하라?

--10.모든 사원의 급여를 100증가하라?

--11.사원번호 7902의 상급자사원번호를 7654, 부서번호를 30으로 바꾸라?

--12.지역이 DALLAS인 사원들의 급여를 10감하라?

--13.급여등급이 2인 사원들의 급여를 20감하라?

--14.사원번호 7499가 퇴사하였다.

--15.부서번호50,부서이름'PLANNING',지역 'MIAMI'가 추가되었다.

--16.부서번호가 40인 부서가 60으로 변경되었다.

--17.부서번호가 30인 부서가 폐지 되었다.

--18.DEPT1 테이블에 없는 부서번호들을 갖고 있는 사원들의 부서번호를 99로변경하라?

--19.EMP1에서 99번 부서번호를 삭제하라

--20.상급자 사원번호가 없는 사원의 급여를 100올렸다.

--21.JONES,JOSH,CLARJ가 부서번호를 30번부서로 바뀌었다.

--22.커미션이 NULL인 데이터를 0으로 바꾸어라?

--23.EMP1전체 테이블을 삭제하라?
