--현재계정의 테이블을 살피는 명령문
SELECT TABLE_NAME
FROM USER_TABLES;

--테이블의 현황을 모니터하는 명령어는?
SELECT *
FROM EMP;

SELECT *
FROM DEPT;

SELECT *
FROM SALGRADE;
SELECT *
FROM BONUS;

--테이블의 구조를 보여주는 명령어는?
DESC BONUS;

--사원테이블에서 직무와 급여를 출력하라?
SELECT JOB,SAL
FROM EMP;

--사원테이블에서 직무의 종류를 중복을 피하여 출력하라
SELECT DISTINCT JOB
FROM EMP;

--사원테이블에서 사원번호와 사원이름을 합쳐서 출력하라
SELECT EMPNO ||'의 '|| ENAME -- 합침!
FROM EMP;

SELECT * FROM EMP;
--COMM이 널이 아닌 값만 출력하라!
SELECT *
FROM EMP
WHERE COMM IS NOT NULL;

SELECT EMPNO AS 사원번호,ENAME AS 사원이름 -- AS 생략 가능.
FROM EMP;

--사원테이블에서 직무가 SALES인 사원의 정보를 출력하라?
SELECT *
FROM EMP
WHERE JOB='SALESMAN';

SELECT * FROM EMP;
--사원테이블에서 SAL이 1000-2000사이인 사원을 출력하라?
SELECT *
FROM EMP
WHERE SAL NOT BETWEEN 1000 AND 2000;

--사원테이블에서 직무가 점원이거나 영업사원인 경우를 출력하라?
SELECT *
FROM EMP
WHERE JOB NOT IN('CLERK','SALESMAN');

--단일행함수?
SELECT ABS(-100),ROUND(123,456,2),
CELL(-3.1),TRUNC(123.99956),FLOOR(3.998),FLOOR(-3.1)
FROM DUAL;

SELECT LOWER('ABCDEFG'),
UPPER('abcdefg') FROM DUAL;

SELECT INITCAP('abcdef defghi') FROM DUAL;
SELECT SUBSTR('ABCDEFG',3,2) FROM DUAL;
SELECT LENGTH('abcdefg') FROM DUAL;
SELECT INSTR('oRacle','c') from dual;
SELECT LPAD(ENAME,15,'#') FROM EMP;
SELECT RPAD(ENAME,15,'#') FROM EMP;
SELECT TRIM('O' FROM 'ORACLE') FROM DUAL;
SELECT SYSDATE+1 FROM DUAL;
SELECT LAST_DAY(SYSDATE) FROM DUAL;

SELECT * FROM EMP;
SELECT ENAME,SAL,COMM,NVL(COMM,0) FROM EMP;
SELECT ENAME,NVL2(COMM,SAL+COMM,SAL) AS SALARY
FROM EMP;

SELECT * FROM EMP;
--사원테이블에서 직무별로 평균급여를 출력하라?
SELECT DEPTNO,ROUND(STDDEV(SAL),1)
FROM EMP
GROUP BY DEPTNO -- group 함수가 쓰여짐으로써...
ORDER BY 2; -- 오름차순!

SELECT MAX(SAL),MIN(SAL),MEDIAN(SAL),AVG(SAL),STDDEV(SAL)
ROUND(STDDEV(SAL))
FROM EMP;

--사원테이블에서 직무별 평균급여가 2000이상인 사원들의 정보를 출력하라
SELECT JOB,ROUND(AVG(SAL),1)
FROM EMP
GROUP BY JOB
HAVING AVG(SAL)>=2000;

