--JOIN()의 실전문제...
--1. 사원테이블과 부서테이블을 NATURAL JOIN으로 진행하라?
SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM EMP NATURAL JOIN DEPT;
--2. 위의 내용을 전통구성인 조인문으로 진행하라?(EQUAL JOIN)
SELECT EMP.DEPTNO,DNAME,ENAME
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO;
--3. 위의 내용을 테이블에서 사원번호,사원이름,부서이름을 검색하라(NATURAL JOIN)
SELECT EMPNO,ENAME,DEPTNO
FROM EMP NATURAL JOIN DEPT;
--4. 사원번호, 사원이름, 부서이름을 검색하라(JOIN~USING)
SELECT EMPNO,ENAME,DNAME FROM EMP JOIN DEPT USING(DEPTNO);
--5. 위의 내용을 JOIN~ON으로 검색하라?
SELECT EMPNO,DEPT.DEPTNO,ENAME,DNAME FROM EMP JOIN DEPT ON(EMP.DEPTNO=DEPT.DEPTNO);
--6. 지역이 NEW YORK인 사원이름을 검색하라?(EQUAL JOIN)
SELECT ENAME
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO
AND LOC='NEW YORK';
--7. 위의 내용을 NATURAL JOIN으로 수행하라?
SELECT A.ENAME
FROM EMP A JOIN DEPT B ON(A.DEPTNO=B.DEPTNO)
WHERE LOC='NEW YORK'
ORDER BY EMPNO;
--8. 위의 내용을 JOIN~USING으로 검색하라?

--9. 위의 내용을 JOIN~ON으로 검색하라?

--10. 지역이 NEW YORK인 사원의 사원번호, 사원이름을 사원번호 순으로 검색하라?
SELECT EMPNO,ENAME
FROM EMP,DEPT
WHERE EMP.DEPTNO=DEPT.DEPTNO
AND LOC='NEW YORK'
ORDER BY EMPNO;

--11.ADAMS사원이 근무중인 부서이름과 지역을 검색하라?(EQUAL JOIN)
--12.위의 내용을 JOIN~USING로 검색하라?
--13.위의 내용을 JOIN~ON으로 검색하라?
--14.위의 내용을 NATURAL JOIN으로 검색하라?
--15.급여가 2000이상인 사원들의 사원명과 지역을 검색하라?
--[EQUAL JOIN/NATURAL JOIN/JOIN~USING/JOIN~ON]

--16.급여가 1000이상 2000이하인 사원들의 사원번호,사원이름
--사원번호 순으로 검색하라?
--[EQUAL JOIN/NATURAL JOIN/JOIN~USING/JOIN~ON]


--17.사원직무가 SALESMAN이면서 CHICAGO지역에 근무중인 사원명을 검색하라?
--[EQUAL JOIN/NATURAL JOIN/JOIN~USING/JOIN~ON]

--18.NEW YORK이나 DALLAS지역에 근무하는 사원들의 사원번호와 사원이름을 사원번호
--검색하라?(EQUAL JOIN)

--19.부서이름이 ACCOUNTING이거나 지역이 CHICAGO인 사원의 사원번호와 사원이름을
--검색하라?(EQUAL JOIN)

--20.18번 문제를 NATURAL JOIN으로 검색하라?

--HAVING절은 GROUP BY절에서 조건이 필요한 시나리오가 있을때 사용됨.
--예1)기계과 학생들중 학년별 평균신장이 160이상인 학년과 평균신장을 구하라?
SELECT STU_GRADE,ROUND(AVG(STU_HEIGHT),1) AHT
FROM STUDENT
WHERE STU_DEPT='기계'
GROUP BY STU_GRADE HAVING AVG(STU_HEIGHT)>=160;

--예2)최대신장이 175이상인 학과와 학과별 최대신장을 구하라?
SELECT STU_DEPT,MAX(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT HAVING MAX(STU_HEIGHT)>=175;

--21.19번 문제를 NATURAL JOIN으로 진행하라?
SELECT EMPNO,ENAME,DNAME,LOC
FROM EMP NATURAL JOIN DEPT
WHERE DNAME='ACCOUNTING' AND LOC='CHICAGO'
ORDER BY 2;
--22.사원번호, 사원이름, 급여, 급여등급을 급여등급별 사원번호 순으로 검색하라?
SELECT EMPNO,ENAME,SAL,GRADE
FROM EMP,SALGRADE
WHERE SAL BETWEEN LOSAL AND HISAL
ORDER BY GRADE,EMPNO;

--23.사원번호 사원이름, 상급자사원번호, 상급자 이름을 검색하라(EQUAL JOIN)
SELECT * FROM EMP;
SELECT A.EMPNO 사원번호,A.ENAME 사원이름,B.EMPNO 상급자사원번호,B.ENAME 상급자사원이름
FROM EMP A,EMP B 
WHERE A.MGR=B.EMPNO;
--24.위의 내용을 JOIN~ON으로 검색하라?
SELECT * FROM EMP;
SELECT A.EMPNO 사원번호,A.ENAME 사원이름,B.EMPNO 상급자사원번호,B.ENAME 상급자사원이름
FROM EMP A JOIN EMP B ON(A.MGR=B.EMPNO);
--25.BLAKE사원보다 많은 급여를 받는 사원이름을 검색하라(부질의)
SELECT ENAME
FROM EMP
WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='BLAKE');
--26.위의 내용을 SELF JOIN으로 진행하시오?
SELECT B.ENAME,B.SAL
FROM EMP A, EMP B
WHERE B.SAL>A.SAL
AND ENAME='BLAKE';
--27.FORD사원과 같은 부서에 근무하는 사원이름을 검색하라?
SELECT ENAME
FROM EMP
WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='FORD')
AND ENAME<>'FORD';
SELECT DEPTNO FROM EMP WHERE ENAME='FORD';
SELECT ENAME FROM EMP WHERE DEPTNO=20;
--28.FORD사원과 같은 급여를 받는 사원과 사원번호를 검색하라?
SELECT EMPNO, ENAME
FROM EMP
WHERE SAL=(SELECT SAL FROM EMP WHERE ENAME='FORD');
--29.부서별 인원수를 부서이름과 함께 사원이 많은 부서순으로 검색하라?
SELECT DNAME,COUNT(*)
FROM EMP NATURAL JOIN DEPT
GROUP BY DNAME
ORDER BY 2 DESC;
--30.사원번호, 사원이름을 부하직원 수가 많은 순으로 검색하라?
SELECT B.EMPNO,B.ENAME,COUNT(*)
FROM EMP A JOIN EMP B ON(A.MGR=B.EMPNO)
GROUP BY B.EMPNO,B.ENAME
ORDER BY 3 DESC;
--31.부서이름이 'SALES'이면서 사원직무가 'MANAGER'인 사원의 사원번호, 사원이름을
--사원이름 순으로 검색하라?
SELECT EMPNO,ENAME
FROM EMP NATURAL JOIN DEPT
WHERE DNAME='SALES' AND JOB='MANAGER'
ORDER BY 2;
--32.SCOTT사원보다 많은 급여를 받는 사원정보를 검색하라?
SELECT * FROM EMP
WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='SCOTT');
--33.ALLEN사원보다 적은 급여를 받는 사원정보를 검색하라?
SELECT * FROM EMP
WHERE SAL<(SELECT SAL FROM EMP WHERE ENAME='ALLEN');
SELECT SAL FROM EMP WHERE ENAME='ALLEN';
--34.20번 부서사원의 사원직무와 같은 다른부서의 사원직무를 검색하라?
SELECT *
FROM EMP
WHERE JOB IN(SELECT JOB FROM EMP WHERE DEPTNO=20)
AND DEPTNO<>20;
--35.전체사원의 평균급여보다 급여가 많은 사원정보를 검색하라?
SELECT * FROM EMP
WHERE SAL>(SELECT AVG(SAL) FROM EMP);
SELECT AVG(SAL) FROM EMP;
--36.급여가 모든 부서들의 평균급여보다 많은 사원정보를 검색하라?
SELECT * FROM EMP
WHERE SAL>ALL(SELECT AVG(SAL)
FROM EMP GROUP BY DEPTNO);
SELECT AVG(SAL) FROM EMP WHERE DEPTNO IN(10,20,30);
--37.20번 부서의 최대급여보다 최대 급여가 큰 부서의 번호와 최대급여를 검색하라?
SELECT DEPTNO,MAX(SAL)
FROM EMP
WHERE SAL>(SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO HAVING DEPTNO=20)
GROUP BY DEPTNO;
--38.CHICAGO지역에 근무하는 위치하는 부서에서 근무하는 사원정보를 검색하라(단 부질의 사용할것)
SELECT * FROM EMP WHERE DEPTNO=(SELECT DEPTNO
FROM DEPT WHERE LOC='CHICAGO');

-- HW. C, D, E!